version: '3'

services: 
###############################
#   Setup mongo container
# ###############################
  mongod:
    image: mongo
    expose:
      - "27017"
    ports:
      - "27017:27017"
    volumes:
      - /var/lib/mongodb:/data/db

################################
#   Setup server container
############################### 
  server: 
    build: ./server
    volumes: 
      - ./server:/usr/src/app 
    ports: 
      - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
    expose:
      - ${APP_SERVER_PORT}
    depends_on:
      - mongod

###############################
#   Setup client container
###############################
  client: 
    build: ./client
    volumes: 
      - ./client:/usr/src/app 
    ports: 
      - ${REACT_APP_PORT}:${REACT_APP_PORT}
    depends_on: 
      - server

#APP_SERVER_PORT are enviroment variables stored in the
#.env file in the same folder level as docker-compose. 
#no need to use dotenv as docker automatically looks for it 