version: '3'

services: 
  
  server: 
    build: ./server
    volumes: 
      - ./server:/usr/src/app 
    ports: 
      - ${APP_SERVER_PORT}:${APP_SERVER_PORT}

  client: 
    build: ./client
    volumes: 
      - ./client:/usr/src/app 
    ports: 
      - ${REACT_APP_PORT}:${REACT_APP_PORT}
    depends_on: 
      - server
